### ISSUE TITLE
Calibration error!

### ISSUE THREAD

**Issue by enzodello** [kubi48/TransistorTester-source#8]
Ho Markus, with last version of your firmware, I am unable to complete the calibration procedure, I always end up getting an error.
I use an atmega328p, without bootloader, and before starting the calibration procedure, I carry out three measurements of a 1uf capacitor.
I had no problems with versions prior to 1.40, do you have any suggestions for me?

**Comment by madires** [comment]
That's a known issue. Please replace cap.c with [cap.c-1.51m.tgz](https://github.com/madires/Transistortester-Warehouse/blob/master/Firmware/m-firmware/cap.c-1.51m.tgz).
